import { Link } from "react-router-dom";
import { ArrowRight, Play, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { LaneBadge } from "@/components/LaneBadge";

const includedModules = [
  { label: "KYC – Individual Onboarding & Screening", href: "/platform/kyc-kyb" },
  { label: "KYB – Business Entity Screening", href: "/platform/kyc-kyb" },
  { label: "AML Screening & Monitoring", href: "/platform/aml-screening" },
  { label: "Risk Assessment & Categorisation", href: "/platform/risk-assessment" },
  { label: "Transaction Monitoring", href: "/platform/transaction-monitoring" },
  { label: "Regulatory Reporting (CRS, FATCA, FINTRAC)", href: "/platform/regulatory-reporting" },
  { label: "Logs & Audit Trail", href: "/platform/suite" },
];

export const SuiteHeroSection = () => {
  return (
    <section className="section-padding bg-background">
      <div className="container-enterprise">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div>
            <LaneBadge lane="platform" className="mb-6" />
            <h1 className="text-display text-navy mb-4">
              WorldAML Suite
            </h1>
            <p className="text-body-lg text-teal font-medium mb-6">
              Core AML Compliance Workflows in a Unified Interface
            </p>
            <p className="text-body-lg text-text-secondary mb-8">
              WorldAML Suite is a compliance platform designed to support essential 
              AML workflows, including KYC, KYB, AML screening, monitoring, and risk 
              assessment. Built for regulated institutions that require core compliance 
              functionality without unnecessary modules.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4">
              <Button size="lg" asChild>
                <Link to="/get-started">
                  Request Platform Access
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" asChild>
                <Link to="/demo">
                  <Play className="mr-2 h-4 w-4" />
                  Request Demo
                </Link>
              </Button>
            </div>
          </div>
          
          <div className="bg-surface-subtle rounded-xl p-8 border border-divider">
            <h3 className="text-lg font-semibold text-navy mb-6">
              Included Modules
            </h3>
            <ul className="space-y-4">
              {includedModules.map((module) => (
                <li key={module} className="flex items-start gap-3">
                  <CheckCircle2 className="w-5 h-5 text-teal flex-shrink-0 mt-0.5" />
                  <span className="text-text-secondary">{module}</span>
                </li>
              ))}
            </ul>
            <div className="mt-8 pt-6 border-t border-divider">
              <p className="text-sm text-text-tertiary">
                Screening results are generated by approved third-party data sources 
                and presented for review and governance purposes.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SuiteHeroSection;
