import { Link } from "react-router-dom";
import { ArrowRight, Play, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";

export const SuiteCTASection = () => {
  return (
    <section className="section-padding bg-navy">
      <div className="container-enterprise">
        {/* Mandatory Clarification */}
        <div className="max-w-3xl mx-auto mb-12 p-6 rounded-lg border border-white/10 bg-white/5">
          <div className="flex gap-4">
            <AlertCircle className="w-6 h-6 text-accent flex-shrink-0" />
            <div>
              <h4 className="text-body font-semibold text-white mb-2">Important Clarification</h4>
              <p className="text-body-sm text-slate-light">
                WorldAML Suite does not own or publish sanctions, PEP, or adverse media data. 
                All screening results are generated by approved third-party data sources 
                and presented for review and governance purposes.
              </p>
            </div>
          </div>
        </div>

        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-headline text-white mb-4">
            Request Platform Access
          </h2>
          <p className="text-body-lg text-slate-light mb-8">
            Get started with WorldAML Suite to support your core AML compliance 
            workflows. Request a demo to see how the platform works for your organisation.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" variant="accent" asChild>
              <Link to="/get-started">
                Request Platform Access
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline-light" asChild>
              <Link to="/demo">
                <Play className="mr-2 h-4 w-4" />
                Request Demo
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SuiteCTASection;
