import { Link } from "react-router-dom";
import { ArrowRight, FileText, Info, BookOpen } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CrossSellCard } from "@/components/CrossSellCard";

export const APICTASection = () => {
  return (
    <section className="section-padding bg-navy">
      <div className="container-enterprise">
        {/* Mandatory Clarification */}
        <div className="max-w-3xl mx-auto mb-12">
          <div className="bg-white/10 border border-white/20 rounded-lg p-6">
            <div className="flex items-start gap-4">
              <Info className="h-5 w-5 text-teal-light mt-0.5 flex-shrink-0" />
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">
                  Important Information
                </h3>
                <p className="text-slate-light text-sm leading-relaxed">
                  WorldAML API does not provide screening data. All screening results 
                  are generated by integrated third-party data sources selected according 
                  to jurisdiction and customer requirements.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* EDD cross-sell */}
        <div className="max-w-3xl mx-auto mb-10">
          <CrossSellCard
            variant="inline"
            domain="duediligenceworld.com"
            destPath="/request"
            utmSource="worldaml.com"
            utmMedium="api-page-cta"
            utmCampaign="edd-escalation"
            accentColor="hsl(260 40% 45%)"
            icon={<BookOpen className="w-4 h-4" />}
            eyebrow="Due Diligence World"
            headline="Need a narrative EDD pack for escalations?"
            body="When your API flags a high-risk entity, our analysts produce a regulatory-grade EDD report — sourced, written, and delivered in 48–72 hours."
            ctaLabel="Request an EDD report"
          />
        </div>

        <div className="max-w-3xl mx-auto text-center">
          <h2 className="text-headline text-white mb-4">
            Ready to Integrate?
          </h2>
          <p className="text-body-lg text-slate-light mb-8">
            Request API access to start building with WorldAML. Our team will 
            provide sandbox credentials, documentation, and technical support.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button size="lg" variant="accent" asChild>
              <Link to="/get-started">
                Request API Access
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button size="lg" variant="outline-light" asChild>
              <a 
                href="https://worldaml.readme.io" 
                target="_blank" 
                rel="noopener noreferrer"
              >
                <FileText className="mr-2 h-4 w-4" />
                View Documentation
              </a>
            </Button>
          </div>
        </div>
      </div>
    </section>
  );
};

export default APICTASection;
