import Header from "@/components/Header";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";
import { AMLApiHeroSection } from "@/components/aml-api/AMLApiHeroSection";
import { AMLApiWhatIsSection } from "@/components/aml-api/AMLApiWhatIsSection";
import { AMLApiEndpointsSection } from "@/components/aml-api/AMLApiEndpointsSection";
import { AMLApiIntegrationSection } from "@/components/aml-api/AMLApiIntegrationSection";
import { AMLApiUseCasesSection } from "@/components/aml-api/AMLApiUseCasesSection";
import { AMLApiCTASection } from "@/components/aml-api/AMLApiCTASection";

const faqStructuredData = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: [
    {
      "@type": "Question",
      name: "What is an AML screening API?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "An AML screening API allows businesses to programmatically check individuals and companies against global sanctions lists, PEP databases, adverse media sources, and watchlists through a RESTful interface.",
      },
    },
    {
      "@type": "Question",
      name: "How fast is the WorldAML AML API?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "WorldAML's AML API delivers sub-200ms average response times for individual screening requests, with batch endpoints available for high-volume re-screening.",
      },
    },
    {
      "@type": "Question",
      name: "Does WorldAML provide the screening data?",
      acceptedAnswer: {
        "@type": "Answer",
        text: "No. WorldAML acts as an orchestration layer. All screening results are generated by approved third-party data sources selected based on jurisdiction and customer requirements.",
      },
    },
  ],
};

const softwareStructuredData = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "WorldAML AML Screening API",
  applicationCategory: "BusinessApplication",
  operatingSystem: "Web",
  description: "RESTful API for automated AML screening including sanctions, PEPs, adverse media, and ongoing monitoring.",
  url: "https://www.worldaml.com/aml-api",
  offers: {
    "@type": "Offer",
    category: "API Access",
    url: "https://www.worldaml.com/get-started",
  },
};

const AMLApiPage = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <SEO
        title="AML Screening API — Automate Compliance at Scale"
        description="Integrate real-time AML screening into your workflows. Screen against sanctions lists, PEP databases, adverse media, and RCAs through a single RESTful API."
        canonical="/aml-api"
        breadcrumbs={[
          { name: "Home", url: "/" },
          { name: "AML API", url: "/aml-api" },
        ]}
        structuredData={[faqStructuredData, softwareStructuredData]}
      />
      <Header />
      <main className="flex-1">
        <AMLApiHeroSection />
        <AMLApiWhatIsSection />
        <AMLApiEndpointsSection />
        <AMLApiIntegrationSection />
        <AMLApiUseCasesSection />
        <AMLApiCTASection />
      </main>
      <Footer />
    </div>
  );
};

export default AMLApiPage;
