import Header from "@/components/Header";
import Footer from "@/components/Footer";

const Terms = () => {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />
      <main className="flex-1">
        {/* Hero */}
        <section className="section-padding bg-navy">
          <div className="container-enterprise">
            <div className="max-w-3xl">
              <p className="text-label text-slate-light mb-4">Terms of Service</p>
              <h1 className="text-display text-white mb-6">
                Terms of Use
              </h1>
              <p className="text-body-lg text-slate-light">
                Navigate The Path Forward With Confidence. WorldAML is a product of InfoCredit Group Ltd.
              </p>
            </div>
          </div>
        </section>

        {/* Content */}
        <section className="section-padding">
          <div className="container-enterprise">
            <div className="max-w-4xl mx-auto prose prose-slate">
              <div className="bg-surface-subtle border border-divider rounded-lg p-6 mb-8">
                <p className="text-body text-text-secondary font-semibold">
                  PLEASE READ THIS LEGAL NOTICE CAREFULLY BEFORE USING THIS SITE
                </p>
                <p className="text-body text-text-secondary mt-2">
                  By using this site, you signify your assent to these terms of use. If you do not agree to these terms of use, please do not use the site.
                </p>
              </div>

              <p className="text-body text-text-secondary">
                <strong>WorldAML</strong> is a product of <strong>InfoCredit Group Ltd</strong> (referred to as "InfoCredit," "we," "us," or "our" herein), a company registered in Cyprus with its main office at 5a Philippou Chatzigeorgiou Str., Nicosia, Cyprus.
              </p>

              <h2 className="text-headline text-navy">Restrictions On Use Of Materials</h2>
              <p className="text-body text-text-secondary">
                This site is owned and operated by InfoCredit Group Ltd. No material from the site may be copied, reproduced, republished, uploaded, posted, transmitted or distributed in any way, except that you may download one copy of the materials on any single computer for your non-commercial use only, provided that you keep intact all copyright and other proprietary notices.
              </p>
              <p className="text-body text-text-secondary">
                Modification of the materials or use of the materials for any other purpose is a violation of InfoCredit's copyright and other proprietary rights. The use of any such material on any other website or networked computer environment is prohibited.
              </p>
              <p className="text-body text-text-secondary">
                All trademarks, service marks and trade names displayed on this site, except for those of other companies, are proprietary to InfoCredit Group Ltd and WorldAML.
              </p>

              <h2 className="text-headline text-navy">Software License</h2>
              <p className="text-body text-text-secondary">
                In the event that you download any software from the site, the software, including any files, images incorporated in or generated by the software, and data accompanying the software (collectively, the "Software") are non-exclusively licensed to you by InfoCredit. InfoCredit does not transfer title of the Software to you. InfoCredit retains full and complete title to the Software, and all intellectual property rights therein.
              </p>
              <p className="text-body text-text-secondary">
                You may not redistribute, sell, decompile, reverse engineer, disassemble, or otherwise reduce the Software to a human-perceivable form.
              </p>

              <h2 className="text-headline text-navy">Disclaimer</h2>
              <p className="text-body text-text-secondary">
                The materials on this site are provided "as is" and without warranties of any kind either express or implied. To the fullest extent permissible pursuant to applicable law, InfoCredit disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose.
              </p>
              <p className="text-body text-text-secondary">
                InfoCredit does not warrant that the functions contained in the materials will be uninterrupted or error-free, that defects will be corrected, or that this site or the server that makes it available are free of viruses or other harmful components.
              </p>
              <p className="text-body text-text-secondary">
                InfoCredit does not warrant or make any representations regarding the use or the results of the use of the materials in this site in terms of their correctness, accuracy, reliability, or otherwise. You (and not InfoCredit) assume the entire cost of all necessary servicing, repair, or correction.
              </p>

              <h2 className="text-headline text-navy">Limitation Of Liability</h2>
              <p className="text-body text-text-secondary">
                Under no circumstances, including, but not limited to, negligence, shall InfoCredit be liable for any special or consequential damages that result from the use of, or the inability to use, the materials in this site, even if InfoCredit or an InfoCredit authorized representative has been advised of the possibility of such damages.
              </p>
              <p className="text-body text-text-secondary">
                In no event shall InfoCredit have any liability to you for damages, losses and causes of action – whether in contract, tort (including, but not limited to, negligence), or otherwise – for accessing this site.
              </p>

              <h2 className="text-headline text-navy">Jurisdiction</h2>
              <p className="text-body text-text-secondary">
                All claims, disputes or disagreements which may arise out of the interpretation, performance or in any way relating to your use of this site and any and all other InfoCredit site(s), shall be submitted exclusively to the jurisdiction of the courts located in the Republic of Cyprus.
              </p>

              <h2 className="text-headline text-navy">Contact Us</h2>
              <div className="bg-surface-subtle border border-divider rounded-lg p-6">
                <p className="text-body text-text-secondary">
                  <strong>InfoCredit Group Ltd</strong><br />
                  Philippou Hadjigeorgiou 5A, Acropolis<br />
                  Nicosia 2006, Cyprus<br />
                  <strong>Telephone:</strong> +357 22398000<br />
                  <strong>Email:</strong> info@infocreditgroup.com
                </p>
              </div>

              <p className="text-caption text-text-tertiary mt-8">
                Last updated: February 2025
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
};

export default Terms;
