const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const GATEWAY_URL = 'https://ai.gateway.lovable.dev/v1/chat/completions'

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders })

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    )
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

    const { rule_id } = await req.json()
    if (!rule_id) return new Response(JSON.stringify({ error: 'rule_id required' }), { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

    // Fetch the rule
    const { data: rule, error: ruleErr } = await supabase
      .from('suite_alert_rules')
      .select('*')
      .eq('id', rule_id)
      .eq('user_id', user.id)
      .single()

    if (ruleErr || !rule) return new Response(JSON.stringify({ error: 'Rule not found' }), { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })

    // Fetch transactions sample to evaluate rule against
    const { data: txs } = await supabase
      .from('suite_transactions')
      .select('amount, currency, direction, counterparty, counterparty_country, risk_flag, description, created_at')
      .eq('user_id', user.id)
      .order('created_at', { ascending: false })
      .limit(200)

    // Fetch alerts generated by this rule
    const { data: alerts } = await supabase
      .from('suite_alerts')
      .select('id, severity, status, created_at')
      .eq('user_id', user.id)
      .eq('rule_id', rule_id)

    const apiKey = Deno.env.get('LOVABLE_API_KEY')
    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'AI not configured' }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const prompt = `You are a senior AML/CFT compliance analyst. Analyse this alert rule in depth.

RULE:
- Name: ${rule.name}
- Severity: ${rule.severity}
- Active: ${rule.is_active}
- Conditions: ${JSON.stringify(rule.conditions)}

TRANSACTION PORTFOLIO (${txs?.length || 0} recent transactions, sample):
${JSON.stringify((txs || []).slice(0, 40), null, 1)}

ALERTS GENERATED BY THIS RULE: ${alerts?.length || 0}

Respond ONLY with valid JSON in this exact format:
{
  "effectiveness_score": 75,
  "risk_coverage": "high|medium|low",
  "summary": "2-3 sentence assessment of this rule's effectiveness",
  "strengths": ["strength 1", "strength 2"],
  "weaknesses": ["weakness 1", "weakness 2"],
  "false_positive_risk": "high|medium|low",
  "false_positive_explanation": "Why false positives may or may not occur",
  "regulatory_alignment": ["FATF Rec 20", "EU 6AMLD Art 3"],
  "estimated_hit_rate": "X% of transactions would trigger this rule",
  "improvement_suggestions": [
    {"suggestion": "description", "priority": "high|medium|low", "rationale": "why this matters"}
  ],
  "similar_rules_to_consider": [
    {"name": "Suggested complementary rule", "conditions_summary": "brief description"}
  ]
}

Guidelines:
- Be specific about which transactions would match this rule
- Consider AML/CFT best practices and FATF recommendations
- Evaluate if thresholds are appropriate for the transaction portfolio
- Identify gaps in coverage
- Score effectiveness 0-100 based on precision, recall, and regulatory alignment`

    const aiRes = await fetch(GATEWAY_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${apiKey}` },
      body: JSON.stringify({
        model: 'google/gemini-2.5-flash',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.3,
        response_format: { type: 'json_object' },
      }),
    })

    if (!aiRes.ok) {
      const errText = await aiRes.text()
      console.error('AI error:', errText)
      return new Response(JSON.stringify({ error: 'AI analysis failed' }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const aiData = await aiRes.json()
    const content = aiData.choices?.[0]?.message?.content
    if (!content) {
      return new Response(JSON.stringify({ error: 'Empty AI response' }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
    }

    const analysis = JSON.parse(content)

    return new Response(JSON.stringify({ rule_name: rule.name, rule_severity: rule.severity, alerts_count: alerts?.length || 0, ...analysis }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (err) {
    console.error('Error:', err)
    return new Response(JSON.stringify({ error: 'Internal error' }), { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } })
  }
})
