
WITH c AS (SELECT slug, id FROM public.academy_courses WHERE slug IN (
 'pep-screening-edd','adverse-media-intelligence','beneficial-ownership','crypto-aml','risk-based-approach','sanctions-screening-essentials'))
INSERT INTO public.academy_questions (course_id, question, options, correct_index, explanation, sort_order)
SELECT c.id, v.question, v.options::jsonb, v.correct_index, v.explanation, v.sort_order
FROM c JOIN (VALUES

-- PEP screening & EDD (11-18)
('pep-screening-edd','A client is the adult son of a serving finance minister. How should he be treated?','["No enhanced measures are needed as he holds no office","As a Relative or Close Associate, subject to the same enhanced due diligence as the PEP","Only screened if he transacts above EUR 15,000","Rejected automatically"]',1,'Family members of PEPs are RCAs and attract the same enhanced due diligence as the PEP themselves.',11),
('pep-screening-edd','A PEP declares salary income of EUR 90,000 but transfers EUR 4.2m into the account. What is the correct next step?','["Process the transfer and review at the next periodic review","Pause, request documented source of wealth evidence and escalate to the MLRO","Close the account without explanation","Lower the risk rating because the client is cooperative"]',1,'A material mismatch between declared source of wealth and actual flows must be resolved with documentary evidence and escalated before processing.',12),
('pep-screening-edd','Which of the following is the strongest source-of-wealth evidence?','["The client''s verbal explanation","A signed self-declaration form","Audited company accounts and a notarised sale-of-shares agreement","A LinkedIn profile showing the client''s role"]',2,'Independent, verifiable documents such as audited accounts and executed legal agreements carry the greatest evidential weight.',13),
('pep-screening-edd','How often should a high-risk PEP relationship normally be reviewed?','["Every five years","At least annually","Only when the client requests changes","Never once onboarded"]',1,'High-risk relationships, including PEPs, require review at least annually and on any material trigger event.',14),
('pep-screening-edd','A screening hit returns a PEP with the same name but a different date of birth and nationality. What should you record?','["Confirmed match","Discounted as a false positive with the discriminating data documented","Escalate to the regulator","Leave the alert open indefinitely"]',1,'False positives must be discounted with a written rationale naming the discriminating attributes so the decision is auditable.',15),
('pep-screening-edd','Who must approve the establishment of a PEP relationship?','["Any member of the onboarding team","Senior management","The client''s relationship manager alone","The external auditor"]',1,'Senior management approval is a mandatory element of enhanced due diligence for PEPs.',16),
('pep-screening-edd','What is the correct treatment of a PEP who left office 18 months ago in a high-corruption jurisdiction?','["Automatically de-risk to standard due diligence after 12 months","Apply a risk-based assessment; residual influence may justify continued EDD","Treat as a prohibited client","Remove from screening entirely"]',1,'Cooling-off is risk-based, not automatic. Continuing influence, jurisdiction and sector can justify extended EDD.',17),
('pep-screening-edd','Which record is essential to defend a PEP onboarding decision to a regulator?','["A copy of the marketing brochure","The screening result, source-of-wealth evidence, risk rating and senior-management approval","The relationship manager''s commission statement","Only the passport copy"]',1,'The audit trail must show the screening outcome, evidence gathered, the risk assessment and who approved it.',18),

-- Adverse media (11-18)
('adverse-media-intelligence','An article alleges fraud but names no source and appears only on one anonymous blog. How should it be treated?','["Confirmed adverse media requiring exit","Recorded and assessed, but weighted low for credibility pending corroboration","Ignored and deleted","Reported directly to the regulator"]',1,'Uncorroborated, low-credibility sources are recorded and weighted, not ignored, but they do not alone establish adverse media.',11),
('adverse-media-intelligence','Which factor most increases the relevance of a media hit?','["The article is recent, from a credible outlet and concerns predicate offences","The article is long","The article is in a foreign language","The article mentions the client''s industry"]',0,'Recency, source credibility and a link to predicate offences drive relevance.',12),
('adverse-media-intelligence','A 12-year-old conviction for a minor regulatory breach surfaces. What is the proportionate response?','["Immediate exit","Assess age, severity and remediation; document the rationale for retaining or exiting","Suppress the finding","Escalate to law enforcement"]',1,'Age, severity and subsequent remediation must be weighed and the reasoning documented.',13),
('adverse-media-intelligence','What is the main risk of relying solely on keyword-based media searches?','["It is too expensive","High false-positive volume and missed non-English or non-indexed coverage","It is prohibited by FATF","It only works for corporates"]',1,'Keyword-only searches generate noise and miss coverage outside indexed English-language sources.',14),
('adverse-media-intelligence','Two clients share a common name and one has adverse media. What is required before attributing the hit?','["Nothing, screen the name only","Match on secondary identifiers such as date of birth, nationality or role before attribution","Attribute to both clients","Close both accounts"]',1,'Attribution requires corroborating identifiers; name-only matching is insufficient.',15),
('adverse-media-intelligence','How should adverse media findings feed the customer risk rating?','["They should not affect the rating","Material confirmed findings should raise the rating and trigger enhanced measures","They replace the rating entirely","They only matter at exit"]',1,'Confirmed material findings are a risk driver and should raise the rating and trigger EDD.',16),
('adverse-media-intelligence','What is the correct escalation route for confirmed adverse media suggesting money laundering?','["Notify the client","Internal report to the MLRO for a suspicion assessment","Post on internal chat","Wait for the next annual review"]',1,'A suspicion arising from adverse media must be reported internally to the MLRO without delay.',17),
('adverse-media-intelligence','Why must adverse media screening be ongoing rather than one-off?','["Regulators require daily reports","Risk profiles change; new allegations can emerge after onboarding","Systems delete old results","Clients request it"]',1,'Adverse media is a dynamic risk source, so ongoing monitoring is required.',18),

-- Beneficial ownership (11-18)
('beneficial-ownership','A company is owned 20% each by five holding companies, all controlled by one individual. Is that individual a UBO?','["No, each holding is below 25%","Yes, aggregated indirect ownership and control identify them as UBO","Only if they are a director","Only in the UK"]',1,'Indirect holdings are aggregated and control is assessed substantively, not just by single-layer percentages.',11),
('beneficial-ownership','When no natural person meets the ownership threshold or exercises control, who should be recorded?','["No one","The senior managing official, with the reason documented","The company''s auditor","The largest creditor"]',1,'Where no UBO can be identified, the senior managing official is recorded as a fallback with the rationale evidenced.',12),
('beneficial-ownership','What is the primary AML concern with nominee arrangements?','["They increase tax","They obscure the identity of the real controller","They slow down onboarding","They are always illegal"]',1,'Nominees can conceal the true controller, defeating the purpose of UBO identification.',13),
('beneficial-ownership','A trust is the shareholder of a client company. Which parties must be identified?','["Only the trustee","Settlor, trustees, protector, beneficiaries and any other person exercising control","Only the beneficiaries","None; trusts are exempt"]',1,'For trusts, the full control chain must be identified, not just the trustee.',14),
('beneficial-ownership','Registry data shows an ownership structure that conflicts with the client''s declaration. What should you do?','["Accept the client''s version","Investigate the discrepancy, obtain supporting documents and consider reporting it","Accept the registry version silently","Terminate immediately"]',1,'Discrepancies must be investigated, evidenced and, in many jurisdictions, reported to the registry.',15),
('beneficial-ownership','Which document best evidences an ownership chain?','["A business card","Certified shareholder registers, share certificates and group structure charts","A website ''About us'' page","The client''s email signature"]',1,'Certified corporate records are the primary evidence of ownership chains.',16),
('beneficial-ownership','What does ''control by other means'' typically include?','["Owning office space","Veto rights, golden shares, funding dependence or the power to appoint directors","Being a customer","Holding a bank mandate for petty cash"]',1,'Control can arise from rights and influence, not just shareholding.',17),
('beneficial-ownership','How often should UBO information be refreshed for a high-risk corporate client?','["Never after onboarding","At least annually and on any trigger event such as a change in structure","Every ten years","Only at exit"]',1,'UBO data must be kept current, with at least annual refresh for high-risk clients plus event-driven updates.',18),

-- Risk-based approach (11-18)
('risk-based-approach','Which combination best describes a customer risk score?','["Only geography","Customer type, product, delivery channel, geography and transaction behaviour","Only transaction volume","The relationship manager''s opinion"]',1,'A composite score weighs customer, product, channel, geographic and behavioural dimensions.',11),
('risk-based-approach','What must happen when controls reduce inherent risk?','["Nothing is recorded","The residual risk is assessed against the board-approved risk appetite","Inherent risk is deleted","The client is automatically low risk"]',1,'Residual risk after controls is what is compared with the stated appetite.',12),
('risk-based-approach','A low-risk client suddenly begins receiving payments from a high-risk jurisdiction. What should occur?','["Nothing until the annual review","An event-driven review and possible re-rating with enhanced measures","Immediate SAR without review","Automatic account closure"]',1,'Material changes are trigger events that require an out-of-cycle review and possible re-rating.',13),
('risk-based-approach','What is the purpose of overriding an automated risk score?','["To reduce workload","To apply documented analyst judgement where the model misses context, with approval and rationale","To satisfy sales targets","To hide high-risk clients"]',1,'Overrides are legitimate only when documented, justified and approved.',14),
('risk-based-approach','Which is a valid application of simplified due diligence?','["A PEP with complex structures","A regulated domestic institution in a low-risk product with proven low-risk indicators","Any client who complains about paperwork","A cash-intensive business"]',1,'SDD applies only where a documented assessment shows genuinely lower risk.',15),
('risk-based-approach','What should a business-wide risk assessment inform?','["Only marketing","Policies, controls, resourcing, monitoring rules and training priorities","Only the audit plan","Nothing operational"]',1,'The BWRA drives the whole control framework, not just documentation.',16),
('risk-based-approach','Why must risk models be validated periodically?','["To satisfy IT","To confirm the weightings and thresholds still discriminate risk accurately","To reduce data storage","Because regulators forbid automation"]',1,'Validation and tuning confirm the model still separates high- from low-risk clients.',17),
('risk-based-approach','Who is ultimately accountable for the risk-based framework?','["The onboarding analyst","Senior management and the board","The software vendor","The external auditor"]',1,'Accountability for the framework and appetite rests with senior management and the board.',18),

-- Crypto AML (11-18)
('crypto-aml','A customer deposits funds traced two hops from a sanctioned mixer. What is the correct response?','["Process normally","Freeze pending investigation, document the tracing evidence and escalate to the MLRO","Convert to fiat immediately","Return the funds without records"]',1,'Exposure to sanctioned infrastructure requires holding, evidencing and escalating rather than processing.',11),
('crypto-aml','What does ''exposure'' mean in blockchain analytics?','["The market value of the asset","The proportion of funds linked directly or indirectly to identified risk categories","The number of wallets held","The exchange''s trading volume"]',1,'Exposure measures direct and indirect links between an address and risk-categorised entities.',12),
('crypto-aml','Which behaviour is a classic crypto layering red flag?','["A single transfer to a regulated exchange","Rapid chain-hopping across multiple assets and bridges with no economic rationale","Holding an asset long term","Paying a licensed merchant"]',1,'Rapid, uneconomic hopping between chains and assets is a layering indicator.',13),
('crypto-aml','Under the Travel Rule, what must an originating VASP transmit?','["Only the amount","Originator and beneficiary identifying information alongside the transfer","Only the wallet address","Nothing for transfers under any threshold"]',1,'The Travel Rule requires originator and beneficiary data to accompany qualifying transfers.',14),
('crypto-aml','What is the AML risk of privacy coins?','["They are slower","They obscure transaction history, defeating tracing and exposure analysis","They cannot be sold","They have no market"]',1,'Privacy-enhancing assets break the traceability that underpins crypto AML controls.',15),
('crypto-aml','A customer''s declared profile is retail savings but they move EUR 2m per week in stablecoins. What is required?','["Nothing, stablecoins are low risk","Enhanced due diligence, source-of-funds evidence and consideration of a suspicion report","Increase their limits","Automatic tier upgrade"]',1,'Activity inconsistent with the customer profile triggers EDD and a suspicion assessment.',16),
('crypto-aml','What is the value of a wallet-screening control at withdrawal?','["It speeds up settlement","It prevents sending funds to sanctioned or high-risk addresses","It reduces network fees","It is only cosmetic"]',1,'Screening destination addresses prevents sanctions breaches and exposure to illicit infrastructure.',17),
('crypto-aml','Which record should be retained for a crypto investigation?','["Only the customer''s email","Transaction hashes, tracing output, exposure scores, analyst rationale and escalation decisions","Just the wallet balance","Nothing, blockchains are public"]',1,'A defensible file includes the on-chain evidence plus the analyst reasoning and decisions.',18),

-- Sanctions screening (10-18)
('sanctions-screening-essentials','A payment is stopped on a possible sanctions match. What must not happen?','["Escalating to the sanctions officer","Telling the customer their name matched a sanctions list before clearance","Documenting the alert","Freezing the payment"]',1,'Premature disclosure risks tipping off and may breach sanctions obligations; clearance and reporting come first.',10),
('sanctions-screening-essentials','Why is 50% ownership relevant in sanctions compliance?','["It is a tax threshold","Entities owned 50% or more by designated persons are treated as designated themselves","It sets the screening fuzziness","It applies only to PEPs"]',1,'Under OFAC and similar regimes, majority ownership by designated persons extends the designation.',11),
('sanctions-screening-essentials','What happens if the screening fuzziness threshold is set too high (strict)?','["More false positives","True matches with spelling or transliteration variants may be missed","Nothing changes","Screening becomes illegal"]',1,'Overly strict matching creates false negatives, particularly for transliterated names.',12),
('sanctions-screening-essentials','When must a customer base be rescreened?','["Only at onboarding","Whenever sanctions lists are updated, plus at onboarding and on trigger events","Once a year only","Never"]',1,'List changes require rescreening the existing book, not just new customers.',13),
('sanctions-screening-essentials','What is the correct action on a confirmed sanctions match?','["Return the funds to the sender","Freeze/block the assets or payment and report to the competent authority within the required timeframe","Continue the relationship with monitoring","Ask the client for an explanation first"]',1,'Confirmed matches require blocking or freezing and prompt reporting to the authority.',14),
('sanctions-screening-essentials','Which data quality issue most undermines screening effectiveness?','["Missing marketing preferences","Incomplete or inaccurate names, dates of birth and nationalities","Long addresses","Uppercase text"]',1,'Screening quality depends on the completeness and accuracy of the identifying data submitted.',15),
('sanctions-screening-essentials','What should a sanctions alert file contain?','["Only the final decision","The alert, the list entry, discriminating data, the analyst rationale and the approver","The customer''s photograph only","Nothing; systems retain it"]',1,'A defensible alert file records the evidence, reasoning and approval, not just the outcome.',16),
('sanctions-screening-essentials','Why must screening cover sectoral and directional sanctions, not just asset freezes?','["To reduce alert volume","Because prohibitions can restrict specific activities or sectors even without a full asset freeze","They are identical","Only banks need this"]',1,'Sectoral measures restrict defined dealings, so screening and controls must address them separately.',17),
('sanctions-screening-essentials','Who should approve the discounting of a high-scoring sanctions alert?','["The relationship manager","A trained second reviewer or sanctions officer under four-eyes review","Nobody, it is automatic","The customer"]',1,'High-risk alert dispositions require independent second-line review.',18)

) AS v(slug, question, options, correct_index, explanation, sort_order) ON v.slug = c.slug;
